/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'User' at '16/04/20 21:45' with Gradle 2.9
 *
 * @author User, @date 16/04/20 21:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public boolean errorMethod(){
    	return false;
    }
}
