import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.RandomStringUtils;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'User' at '16/04/20 21:45' with Gradle 2.9
 *
 * @author User, @date 16/04/20 21:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public boolean errorMethod(){
    	return false;
    }

    public boolean randomTest(){
    	List<String> list = new ArrayList<>();
    	for(int i = 0; i < 1000; i++){
    		String str = RandomStringUtils.randomAlphanumeric(11);
    		if(list.contains(str)){
    			return false;
    		}
    		list.add(str);
    	}
    	return true;
    }
}
