import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.RandomStringUtils;
import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'User' at '16/04/20 21:45' with Gradle 2.9
 *
 * @author User, @date 16/04/20 21:45
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testErrorMethod() {
        Library classUnderTest = new Library();
        assertFalse("error test", classUnderTest.errorMethod());
    }

    @Test public void randomTest() {
        Library classUnderTest = new Library();
    	List<String> list = new ArrayList<>();
    	for(int i = 0; i < 1000; i++){
    		String str = RandomStringUtils.randomAlphanumeric(11);
    		System.out.println(str);
    	}
        assertTrue("random error",true);
    }
}
