package com.green;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'User' at '16/04/20 21:45' with Gradle 2.9
 *
 * @author User, @date 16/04/20 21:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public boolean errorMethod(){
    	return false;
    }

    public boolean randomTest(){
    	for(int i = 0; i < 100; i++){
    		StringBuilder sb = new StringBuilder();
    		if(i % 3 == 0){
    			sb.append("Fizz");
    		}
    		if(i % 5 == 0){
    			sb.append("Buzz");
    		}
    		if(sb.length() == 0){
    			sb.append(String.valueOf(i));
    		}
    		System.out.println(sb.toString());
    	}
    	System.out.println("success");
    	System.out.println("success");
    	System.out.println("success");
    	System.out.println("success");
    	return true;
    }

    public void running(){
    	String str = "string";
    	if(str.length() == 5){
    		System.out.println("5");
    	}

    	boolean flg = true;

    	if(flg){

    	}
    }
}
