package com.green;
import static org.junit.Assert.*;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'User' at '16/04/20 21:45' with Gradle 2.9
 *
 * @author User, @date 16/04/20 21:45
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testErrorMethod() {
        Library classUnderTest = new Library();
        assertFalse("error test", classUnderTest.errorMethod());
    }

    @Test public void randomTest() {
        Library classUnderTest = new Library();

        assertTrue("random error",classUnderTest.randomTest());
    }
}
